export const UserRoles = Object.freeze({
  Admin: "Admin",
  Host: "Host",
  Developer: "Developer",
  Mapsetter: "Mapsetter",
  AllStarMapSetter: "All-Star Mapsetter",
  Pooler: "Pooler",
  HeadPooler: "Head Pooler",
  Referee: "Referee",
  Streamer: "Streamer",
  Commentator: "Commentator",
  Captain: "Captain",
  Player: "Player",
  Mapper: "Mapper",
});
