export default {
  en: {
    home: "Home",
    rules: "Rules",
    mappools: "Mappools",
    schedule: "Schedule",
    players: "Players",
    staff: "Staff",
    language: "Language",
    merch: {
      title: "Merch",
      mainStore: "Main Store",
      mousepads: "Mousepads (now down)",
    },
    login: "Log In",
    logout: "Log Out",
    register: "Register",
    discord: "Discord",
    settings: "Settings",
    userSettings: {
      note: "Don't forget the #number in your Discord username (e.g. Naru#1234)",
      discord: "Discord Username",
      timezone: "Timezone",
      tournies: "My Tournies",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "Archives",
    stats: "Statistics",
    information: "Information",
    donate: "Donate",
    submissions: "Entry Submissions",
    songs: "Songs",
    links: "Links",
  },

  ja: {
    home: "ホーム",
    rules: "ルール",
    mappools: "マッププール",
    schedule: "スケジュール",
    players: "プレイヤー",
    staff: "スタッフ",
    language: "言語",
    merch: {
      title: "ストア",
      mainStore: "Main Store",
      mousepads: "Mousepads",
    },
    login: "ログイン",
    logout: "ログアウト",
    register: "登録する",
    discord: "ディスコード",
    userSettings: {
      note: "ユーザー名の#ID番号も入力してください (例: Naru#1234)",
      discord: "ディスコードのユーザー名",
      timezone: "時間帯",
      tournies: "登録している大会",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "アーカイブ",
    stats: "スタッツ",
    information: "参加に関して",
    donate: "支援",
    submissions: "Entry Submissions",
    links: "リンク",
  },

  ko: {
    home: "홈",
    rules: "규칙",
    mappools: "맵풀",
    schedule: "일정",
    players: "참가자 목록",
    staff: "스태프 목록",
    language: "언어",
    merch: {
      title: "상품",
      mainStore: "Main Store",
      mousepads: "Mousepads",
    },
    login: "로그인",
    logout: "로그아웃",
    register: "참가신청",
    discord: "디스코드",
    userSettings: {
      note: "디스코드 유저명 뒤에 #으로 시작하는 태그를 꼭 포함해주세요. (예: Naru#1234)",
      discord: "디스코드 유저명",
      timezone: "시간대",
      tournies: "참여한 토너먼트",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "Archives",
    information: "Information",
    donate: "Donate",
    submissions: "Entry Submissions",
    links: "Links",
  },

  de: {
    home: "Home",
    rules: "Regeln",
    mappools: "Mappools",
    schedule: "Zeitplan",
    players: "Spieler",
    staff: "Mitarbeiter",
    language: "Sprache",
    merch: {
      title: "Merchshop",
      mainStore: "Main Store",
      mousepads: "Mousepads",
    },
    login: "Login",
    logout: "Logout",
    register: "Registrieren",
    discord: "Discord",
    userSettings: {
      note: "Vergesst nicht die #Zahl in eurem Discord Benutzernamen (z. Bsp. Naru#1234)",
      discord: "Discord Benutzername",
      timezone: "Zeitzone",
      tournies: "Meine Turniere",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "Archives",
    information: "Information",
    donate: "Donate",
    submissions: "Entry Submissions",
    links: "Links",
  },

  ru: {
    home: "Главная страница",
    rules: "Правила",
    mappools: "Маппулы",
    schedule: "Расписание",
    players: "Игроки",
    staff: "Организаторы",
    language: "Язык",
    merch: {
      title: "Мерч",
      mainStore: "Main Store",
      mousepads: "Mousepads",
    },
    login: "Войти",
    logout: "Выйти",
    register: "Зарегистрироваться",
    discord: "Discord",
    userSettings: {
      note: "Не забудьте дописать #цифры после Discord ника (напр. Naru#1234)",
      discord: "Discord ник",
      timezone: "Часовой пояс",
      tournies: "Мои Турниры",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "Archives",
    information: "Information",
    donate: "Donate",
    submissions: "Entry Submissions",
    links: "Links",
  },

  "zh-sg": {
    home: "主页",
    rules: "规则",
    mappools: "铺面",
    schedule: "时间表",
    players: "玩家",
    staff: "职员",
    language: "语言",
    merch: {
      title: "货品",
      mainStore: "Main Store",
      mousepads: "Mousepads",
    },
    login: "登入",
    logout: "登出",
    register: "报名",
    discord: "Discord",
    userSettings: {
      note: "请记得加入discord账号的#编号 (e.g. Naru#1234)",
      discord: "Discord账号",
      timezone: "时间区域",
      tournies: "我的比赛",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "Archives",
    information: "Information",
    donate: "Donate",
    submissions: "Entry Submissions",
    links: "Links",
  },

  fr: {
    home: "Accueil",
    rules: "Règles",
    mappools: "Mappools",
    schedule: "Horaires",
    players: "Participants",
    staff: "Staff",
    language: "Langue",
    merch: {
      title: "Boutique",
      mainStore: "Main Store",
      mousepads: "Mousepads",
    },
    login: "Connexion",
    logout: "Déconnexion",
    register: "Inscription",
    discord: "Discord",
    userSettings: {
      note: "N'oubliez pas votre #nombre dans votre pseudo Discord (ex. Naru#1234)",
      discord: "Pseudo Discord",
      timezone: "Fuseau horaire",
      tournies: "Mes tournois",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "Archives",
    information: "Information",
    donate: "Donations",
    submissions: "Entry Submissions",
    links: "Liens",
  },

  es: {
    home: "Inicio",
    rules: "Reglas",
    mappools: "Mappools",
    schedule: "Horarios",
    players: "Jugadores",
    staff: "Staff",
    language: "Idioma",
    merch: {
      title: "Tienda",
      mainStore: "Main Store",
      mousepads: "Mousepads",
    },
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    register: "Registro",
    discord: "Discord",
    userSettings: {
      note: "No te olvides de tu tag de discord: #número Tag (e.g. Naru#1234)",
      discord: "Nick de Discord",
      timezone: "Zona Horaria",
      tournies: "Mis Torneos",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "Archives",
    information: "Information",
    donate: "Donate",
    submissions: "Entry Submissions",
    links: "Links",
  },

  pl: {
    home: "Strona Główna",
    rules: "Zasady",
    mappools: "Mappool",
    schedule: "Harmonogram",
    players: "Gracze",
    staff: "Kadra",
    language: "Język",
    merch: {
      title: "Merch",
      mainStore: "Main Store",
      mousepads: "Mousepads",
    },
    login: "Zaloguj się",
    logout: "Wyloguj się",
    register: "Zarejestruj się",
    discord: "Discord",
    userSettings: {
      note: "Nie zapomnijcie swojego #numeru przy waszej nazwie na Discordzie (np. Naru#1234)",
      discord: "Nick Discord ",
      timezone: "Strefa Czasowa",
      tournies: "Moje Turnieje",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "Archives",
    information: "Information",
    donate: "Donate",
    submissions: "Entry Submissions",
    links: "Links",
  },

  es_cl: {
    home: "Inicio",
    rules: "Reglas",
    mappools: "Mappools",
    schedule: "Horarios",
    players: "Jugadores",
    staff: "Staff",
    language: "Idioma",
    merch: {
      title: "Tienda",
      mainStore: "Main Store",
      mousepads: "Mousepads",
    },
    login: "Iniciar Sesión",
    logout: "Cerrar Sesión",
    register: "Registro",
    discord: "Discord",
    userSettings: {
      note: "No te olvides de tu tag de discord: #número Tag (e.g. Naru#1234)",
      discord: "Nick de Discord",
      timezone: "Zona Horaria",
      tournies: "Mis Torneos",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "Archives",
    information: "Information",
    donate: "Donate",
    submissions: "Entry Submissions",
    links: "Links",
  },

  nl: {
    home: "Startpagina",
    rules: "Regels",
    mappools: "Mappools",
    schedule: "Schema",
    players: "Spelers",
    staff: "Medewerkers",
    language: "Taal",
    merch: {
      title: "Koopwaar",
      mainStore: "Hoofd winkel",
      mousepads: "Muismatten",
    },
    login: "Inloggen",
    logout: "Uitloggen",
    register: "Registreren",
    discord: "Discord",
    userSettings: {
      note: "Vergeet niet de #nummer in je Discord gebruikersnaam (bijv. Naru#1234)",
      discord: "Discord Gebruikersnaam",
      timezone: "Tijdzone",
      tournies: "Mijn Toernooien",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "Archief",
    information: "Informatie",
    donate: "Doneren",
    submissions: "Entry Submissions",
    links: "Links",
  },
  
  "zh-cn": {
    home: "主页",
    rules: "规则",
    mappools: "图池",
    schedule: "赛程",
    players: "选手",
    staff: "主办成员",
    language: "语言",
    merch: {
      title: "商品",
      mainStore: "主商城",
      mousepads: "鼠标垫",
    },
    login: "登入",
    logout: "登出",
    register: "注册",
    discord: "Discord",
    userSettings: {
      note: "请记得附上discord账号的#编号 (例如：Naru#1234)",
      discord: "Discord账号",
      timezone: "时区",
      tournies: "我的比赛",
      discordLink: "Link",
      discordUpdate: "Update",
    },
    archives: "历史比赛",
    information: "信息",
    donate: "捐赠",
    submissions: "Entry Submissions",
    links: "Links",
  },
};
