export default {
  en: {
    home: "Home",
    rules: "Rules",
    mappools: "Mappools",
    schedule: "Schedule",
    players: "Players",
    staff: "Staff",
    language: "Language",
    merch: "Merch",
    login: "Login",
    logout: "Logout",
    register: "Register",
    discord: "Discord",
    userSettings: {
      note: "Don't forget the #number in your Discord username (e.g. Naru#1234)",
      discord: "Discord Username",
      timezone: "Timezone",
      tournies: "My Tournies",
    },
  },

  ja: {
    home: "ホーム",
    rules: "ルール",
    mappools: "マッププール",
    schedule: "スケジュール",
    players: "プレイヤー",
    staff: "スタッフ",
    language: "言語",
    merch: "ストア",
    login: "ログイン",
    logout: "ログアウト",
    register: "登録する",
    discord: "ディスコード",
    userSettings: {
      note: "ユーザー名の#ID番号も入力してください (例: Naru#1234)",
      discord: "ディスコードのユーザー名",
      timezone: "時間帯",
      tournies: "登録している大会",
    },
  },

  ko: {
    home: "홈",
    rules: "규칙",
    mappools: "맵풀",
    schedule: "일정",
    players: "참가자 목록",
    staff: "스태프 목록",
    language: "언어",
    merch: "상품",
    login: "로그인",
    logout: "로그아웃",
    register: "회원가입",
    discord: "디스코드",
    userSettings: {
      note: "디스코드 유저명 뒤에 #으로 시작하는 태그를 꼭 포함해주세요. (예: Naru#1234)",
      discord: "디스코드 유저명",
      timezone: "시간대",
      tournies: "참여한 토너먼트",
    },
  },

  de: {
    home: "Home",
    rules: "Regeln",
    mappools: "Mappools",
    schedule: "Zeitplan",
    players: "Spieler",
    staff: "Turnierstab",
    language: "Sprache",
    merch: "Merchshop",
    login: "Login",
    logout: "Logout",
    register: "Registrieren",
    discord: "Discord",
    userSettings: {
      note: "Vergesst nicht die #Zahl in eurem Discord Benutzernamen (z. Bsp. Naru#1234)",
      discord: "Discord Benutzername",
      timezone: "Zeitzone",
      tournies: "Meine Turniere",
    },
  },

  ru: {
    home: "Главная страница",
    rules: "Правила",
    mappools: "Маппулы",
    schedule: "Расписание",
    players: "Игроки",
    staff: "Организаторы",
    language: "Язык",
    merch: "Мерч",
    login: "Войти",
    logout: "Выйти",
    register: "Зарегистрироваться",
    discord: "Discord",
    userSettings: {
      note: "Не забудьте дописать #цифры после Discord ника (напр. Naru#1234)",
      discord: "Discord ник",
      timezone: "Часовой пояс",
      tournies: "Мои Турниры",
    },
  },

  zh-sg: {
    home: "主页",
    rules: "规则",
    mappools: "铺面",
    schedule: "时间表",
    players: "玩家",
    staff: "职员",
    language: "语言",
    merch: "货品",
    login: "登入",
    logout: “登出",
    register: "报名",
    discord: "Discord",
    userSettings: {
      note: "请记得加入discord账号的#编号 (e.g. Naru#1234)",
      discord: "Discord账号",
      timezone: "时间区域",
      tournies: "我的比赛",
    },
  },
};
